# Server settings (ServerProperties)
server:
  port: 8080
  address: 0.0.0.0
  sessionTimeout: 30
#  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

management:
  address: 0.0.0.0
  port: 8081

spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    driverClassName: org.postgresql.Driver
#    url: jdbc:mysql://localhost:3306/rlictrl
#    url: jdbc:postgresql://localhost/radius
#    username: root
#    password: 123qwe
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update # create-drop

#for druid datasource
datasource:
  druid:
    driverClassName: com.mysql.jdbc.Driver    
    url: jdbc:mysql://localhost:3306/rlictrl
    username: root
    password: 123qwe


info:
  app:
    name: springtest
    description: spring test
    version: 1.0.0